### ISSUE TITLE
Error for general std::string data

### ISSUE THREAD

**Issue by Multimath** [Jarqwiz/jrle#1]
There is a bug at

https://github.com/Jarqwiz/jrle/blob/7de3b36022b61c626002264066ca06e5e8319abc/jrle.hpp#L43

The code assumes there are no embedded NUL characters, and also that there is a NUL terminator.

See URL https://stackoverflow.com/questions/11752705/does-stdstring-contain-null-terminator
for details.

**Comment by Jarqwiz** [comment]
Thank you for bug report!
It's now fixed.
